# Generated by Django 2.0.5 on 2018-07-05 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=0, max_length=25, null=True)),
                ('body', models.CharField(blank=True, default=0, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=0, max_length=25, null=True)),
                ('image_url', models.CharField(blank=True, default=0, max_length=25, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.Image'),
        ),
    ]
