# Generated by Django 2.0.5 on 2018-07-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_blogpost_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.CharField(blank=True, default=0, max_length=10000, null=True),
        ),
    ]
