# Generated by Django 2.0.5 on 2018-07-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20180705_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
