# Generated by Django 2.0.5 on 2018-07-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0002_auto_20180702_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='type',
            field=models.CharField(blank=True, default=0, max_length=25, null=True),
        ),
    ]
