# Generated by Django 2.0.5 on 2018-07-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0003_album_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=0, max_length=25, null=True)),
                ('image', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('identifier', models.CharField(blank=True, default=0, max_length=25, null=True)),
            ],
        ),
    ]
