# Generated by Django 2.0.5 on 2018-07-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0004_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='type',
            field=models.CharField(blank=True, default=0, max_length=25, null=True),
        ),
    ]
