# Generated by Django 2.0.5 on 2018-07-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0005_artist_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=0, max_length=25, null=True)),
                ('artist', models.CharField(blank=True, default=0, max_length=25, null=True)),
                ('album', models.CharField(blank=True, default=0, max_length=25, null=True)),
                ('track_number', models.CharField(blank=True, default=0, max_length=25, null=True)),
                ('preview_url', models.CharField(blank=True, default=0, max_length=25, null=True)),
                ('duration_ms', models.IntegerField()),
            ],
        ),
    ]
